#!/bin/sh

# remove annoying message macos
export BASH_SILENCE_DEPRECATION_WARNING=1

export XDG_CONFIG_HOME="$HOME/.config"


# Add .local/bin path
export PATH=$PATH:~/.local/bin

# Add cargo/rust binaries
export PATH=$PATH:~/.cargo/bin
# Check https://github.com/rust-lang-nursery/rls
export RUST_SRC_PATH="/home/amoran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src"

# NPM packages in homedir
export NPM_PACKAGES="$HOME/.npm-packages"

# Tell our environment about user-installed node tools
export PATH="$NPM_PACKAGES/bin:$PATH"
# Unset manpath so we can inherit from /etc/manpath via the `manpath` command
unset MANPATH  # delete if you already modified MANPATH elsewhere in your conf
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

# Tell Node about these packages
export NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"

# this is to avoid problems with ctrl-s ctrl-q
stty -ixon

#export $(dbus-launch)

export OLD_TERM=$TERM
export TERM=xterm-256color


export LANGUAGE=en_US.utf-8
export LANG=en_US.utf-8
export LC_ALL=en_US.utf-8
#export LC_MESSAGES=POSIX

export EDITOR="/usr/bin/vim"

# get repo completion
#. ~/Dev/repo.bash_completion/repo.bash_completion

if [ -z ${ZSH_NAME+x} ]; then
  # color prompt green and bold cyan for bash
  PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[00;32m\]\u@\h\[\033[00m\]:\[\033[01;36m\]\w\[\033[00m\]\$ ';
else
  # zsh prompt
  PROMPT='%F{green}%n@%m%f %F{blue}%~%f $ '
fi

function gittree()
{
	git log --graph --all --pretty=format:'%Cred%h%Creset - %Cgreen(%cr)%Creset %s%C(yellow)%d%Creset' --abbrev-commit --date=relative
}

function findgrep()
{
 find . -name $2 -exec grep -nHr "$1" {} \; ;
}

alias glog="git log --oneline"

export KWIN_TRIPLE_BUFFER=1

# cleanup for docker containers
alias docker-cleanup="docker ps -a | grep Exit | cut -d ' ' -f 1 | xargs docker rm"

# Add snaps
export PATH=$PATH:/snap/bin

# Add default go path
export PATH=$PATH:~/go/bin

# Add custom personal path
export PATH=~/.bin:$PATH

# Avoid duplicates in history
export HISTCONTROL=ignoredups

# Common aliases
alias l=ls
alias ll="ls -l"

if [[ `uname` == 'Darwin' ]]
then
# Aliases for macOS
alias python=python3
alias pip=pip3
# Assuming this is zsh, add this to allow vscode terminal to work correctly, as
# explained https://github.com/microsoft/vscode-docs/issues/5221#issuecomment-1061081538
bindkey -e
# This is for the delete key to work in zsh in vscode terminal
bindkey "^[[3~" delete-char
# Prompt in macOS will have different colours. Rationale: this is likely a laptop, so
# it makes sense to distinguish it compared to remote machines.
# for colours, check https://wiki.archlinux.org/title/zsh
PROMPT='%B%F{037}%n@%m%f %b%F{072}%~%f $ '

fi
