#!/bin/sh

export XDG_CONFIG_HOME="$HOME/.config"


# Add cargo/rust binaries
export PATH=$PATH:~/.cargo/bin
# Check https://github.com/rust-lang-nursery/rls
export RUST_SRC_PATH="/home/amoran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src"

# NPM packages in homedir
export NPM_PACKAGES="$HOME/.npm-packages"

# Tell our environment about user-installed node tools
export PATH="$NPM_PACKAGES/bin:$PATH"
# Unset manpath so we can inherit from /etc/manpath via the `manpath` command
unset MANPATH  # delete if you already modified MANPATH elsewhere in your conf
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

# Tell Node about these packages
export NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"

# this is to avoid problems with ctrl-s ctrl-q
stty -ixon

#export $(dbus-launch)

export OLD_TERM=$TERM
export TERM=xterm-256color


export LANGUAGE=en_US.utf-8
export LANG=en_US.utf-8
export LC_ALL=en_US.utf-8
#export LC_MESSAGES=POSIX

export EDITOR="/usr/bin/vim"

# get repo completion
#. ~/Dev/repo.bash_completion/repo.bash_completion

# color prompt green and bold cyan
PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[00;32m\]\u@\h\[\033[00m\]:\[\033[01;36m\]\w\[\033[00m\]\$ '

mergepdf()
{
  dir=${1%/}
  gs -dNOPAUSE -sDEVICE=pdfwrite -sOUTPUTFILE=$dir.pdf  -dPDFSETTINGS=/ebook -dBATCH $dir/*.pdf
}

function findpdf()
{
find . -iname '*.pdf' | while read filename
do
  echo -e "\033[34;1m// === PDF Document:\033[33;1m $filename\033[0m"
  pdftotext -enc ASCII7 "$filename" - | grep --color=always -rni $1
done
}

function gittree()
{
	git log --graph --all --pretty=format:'%Cred%h%Creset - %Cgreen(%cr)%Creset %s%C(yellow)%d%Creset' --abbrev-commit --date=relative
}

function findgrep()
{
 find . -name $2 -exec grep -nHr "$1" {} \; ;
}

alias glog="git log --oneline"


function qvim_launch()
{
 params=$*
 nvim-qt $params > /dev/null 2>&1
}
alias qvim="qvim_launch $@"

export KWIN_TRIPLE_BUFFER=1

#cleanup for docker containers
alias docker-cleanup="docker ps -a | grep Exit | cut -d ' ' -f 1 | xargs docker rm"

# Add snaps
export PATH=$PATH:/snap/bin

# Add custom personal path
export PATH=~/.bin:$PATH

